#image: lambci/lambda:build-nodejs6.10
#image: lambci/lambda:build-nodejs8.10
#image: lambci/lambda:build-nodejs10.x
image: lambci/lambda:build-nodejs12.x

pipelines:
  custom: # Pipelines that can only be triggered manually
    prod-deploy:
      - step:
          name: Test and deploy to production
          deployment: production
          caches:
            - gradle
          services:
            - mysql
          script:
          - npm cache clean -f
          - npm install -g npm@8.14.0
#          - npm install -g serverless --verbose
          - npm install -g serverless
          - npm install serverless-aws-documentation --save-dev
          - java -version
          - which javac
          - ./gradlew build
          - ls -l build/distributions/
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          - serverless deploy --stage prod
  default:
    - step:
        name: Test and deploy to test
        deployment: test
        caches:
          - gradle
        services:
          - mysql
        script:
          - yum -y update
#          - npm cache clean -f
#          - npm install -g npm@8.14.0
#          - npm install -g serverless --verbose
          - npm install -g serverless
          - npm install serverless-aws-documentation --save-dev
          - mkdir ~/jres
          - cd ~/jres
          - tar -xf java-1.8.0-openjdk-portable-1.8.0.322.b06-4.portable.jre.el7.x86_64.tar.xz -C ~/jres
          - ln -s ~/jres/java-1.8.0-openjdk-portable-1.8.0.322.b06-4.portable.jre.el7.x86_64 ~/jres/java-8
          - export JAVA_HOME=~/jres/java-8
          - printenv | grep JAVA_HOME
          - ./gradlew build
          - ls -l build/distributions/
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          - serverless deploy
definitions:
  services:
    mysql:
      image: mysql:5.6
      environment:
        MYSQL_DATABASE: posapps_product_test
        MYSQL_USER: posapps_test
        MYSQL_ROOT_PASSWORD: password
        MYSQL_PASSWORD: password