image: lambci/lambda:build-nodejs6.10
#image: lambci/lambda:build-nodejs8.10
#image: lambci/lambda:build-nodejs8.10-alpine
#image: lambci/lambda:build-nodejs10.15
#image: lambci/lambda:build-nodejs12.16
#image: lambci/lambda:build-nodejs14.16
#image: lambci/lambda:build-nodejs16.9

pipelines:
  custom: # Pipelines that can only be triggered manually
    prod-deploy:
      - step:
          name: Test and deploy to production
          deployment: production
          caches:
            - gradle
          services:
            - mysql
          script:
          - sudo npm cache clear
          - sudo npm install -g serverless --verbose
          - sudo npm install serverless-aws-documentation --save-dev
          - sudo ./gradlew build
          - ls -l build/distributions/
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          - serverless deploy --stage prod
  default:
    - step:
        name: Test and deploy to test
        deployment: test
        caches:
          - gradle
        services:
          - mysql
        script:
          - npm install -g serverless
          - npm install serverless-aws-documentation --save-dev
          - ./gradlew build
          - ls -l build/distributions/
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          - serverless deploy
definitions:
  services:
    mysql:
      image: mysql:5.6
      environment:
        MYSQL_DATABASE: posapps_product_test
        MYSQL_USER: posapps_test
        MYSQL_ROOT_PASSWORD: password
        MYSQL_PASSWORD: password